name: Game Workflow
on:
  workflow_call:
    inputs:
      game:
        required: true
        type: string
      build-command:
        default: "npm run build"
        type: string
jobs:
  game-build-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Goto Directory
      run: cd ./${{ inputs.game }}
    - name: Echo Directory
      run: pwd
    - name: Install dependencies
      run: npm ci
    - name: Build Game
      run: ${{ inputs.build-command }}